name: birdy

channels:
  - defaults
  - conda-forge

dependencies:
  - intake-esm
  - intake-stac>=0.4.0
  - threddsclient==0.4.2
  - openjdk==8.0.152
  - python-flair
  - numpy
  - spacy>=3.5,<4
  - pydantic<2
  - python-levenshtein
  - requests
  - pip>=22
  - pip:
    - textsearch==0.0.21
    - osmnx
    - langchain
    - sentence_transformers
    - chromadb
    - shapely
    - ipywidgets
    - nltk
    - pystac_client
