name: birdy

channels:
  - defaults
  - conda-forge

dependencies:
  - intake-esm==2021.1.15
  - intake-stac==0.3.0
  - sat-search==0.3.0
  - threddsclient==0.4.2
  - openjdk==8.0.152 
  # python-flair=0.8 only works with numpy<=1.19.5
  - python-flair=0.8
  - numpy<=1.19.5
  - spacy==3.1.0
  - python-dateutil==2.7.5
  - python-levenshtein==0.12.2
  - requests=2.25.1
  - pip==20.3.3
  - pip:
    - textsearch==0.0.21
    - spacy==3.1.0
