name: birdy

channels:
- defaults
- conda-forge

dependencies:
- python-flair
- spacy==3.0.6
- numpy<1.20.0
- python-dateutil
- python-levenshtein==0.12.2
- requests=2.25.1
- pip==20.3.3

- pip:
  - textsearch==0.0.21
  - spacy 