name: birdy

channels:
  - defaults
  - conda-forge

dependencies:
  - intake-esm
  - intake-stac==0.3.0
  # avoid conda conflict with python-dateutil 2.8 between unreleased sat-stac and newer pandas
  # (see https://github.com/sat-utils/sat-stac/issues/73 and https://github.com/pdm-project/pdm/issues/2193)
  - sat-search==0.3.0
  - sat-stac>=0.4.1
  - pandas<2
  - python-dateutil
  - threddsclient==0.4.2
  - openjdk==8.0.152
  - python-flair
  - numpy
  - spacy>=3.5,<4
  - pydantic<2
  - python-levenshtein
  - requests
  - pip>=22
  - pip:
    - textsearch==0.0.21
    - osmnx
    - langchain
    - sentence_transformers
    - chromadb
    - shapely
    - ipywidgets
    - nltk
    - pystac_client
