name: birdy

channels:
- defaults
- conda-forge

dependencies:
# - netCDF4==1.5.6
# - jupyterlab==2.2.6
- nb_conda==2.2.1
- nb_conda_kernels==2.3.1
# - ipykernel==5.3.4
# - shapely==1.7.0
# - perl==5.26.2
# - python-flair
# - spacy==3.0.6
- numpy==1.20.0
- python-levenshtein==0.12.2
- requests=2.25.1
- pip==20.3.3

- pip:
  # - threddsclient==0.4.2
  # - birdhouse-birdy==0.7.0
  # - intake-stac==0.3.0
  # - intake-esm==2021.1.15
  # - sat-search==0.3.0
  # - ipywidgets==7.6.3
  # - torch
  # - jpype1==0.6.3
  # - numpy==1.20.0
  - textsearch==0.0.21
  # - flair==0.8
  - spacy 
  - python-dateutil