#!/bin/sh

# Set these paths appropriately

BIN="/home/timea/PycharmProjects/daccs/wp15/nlp/nl2query/heideltime/tree-tagger-linux-3.2.3/bin"
CMD="/home/timea/PycharmProjects/daccs/wp15/nlp/nl2query/heideltime/tree-tagger-linux-3.2.3/cmd"
LIB="/home/timea/PycharmProjects/daccs/wp15/nlp/nl2query/heideltime/tree-tagger-linux-3.2.3/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/english-abbreviations
PARFILE=${LIB}/english.par

$TOKENIZER -e -a $ABBR_LIST $* |
# remove empty lines
grep -v '^$' |
# tagging
$TAGGER $OPTIONS $PARFILE | 
perl -pe 's/\tV[BDHV]/\tVB/;s/\tIN\/that/\tIN/;'
