name: birdy
channels:
  - conda-forge
  - defaults
dependencies:
  - affine
  - gdal
  - geojson
  - intake-stac
  - pyproj
  - rasterio
  - shapely

  # TODO: These next packages could possibly be added to a more generic 'vision' image, from which 'eo' would be built
  - h5py
  - googledrivedownloader
  - pillow>=7.1

  # TODO: These next packages could possibly be added to a more specific 'ML' image, built from the 'eo' image
  - cython
  - ddt
  - gitdb
  - gitpython
  - hdf5plugin
  - lz4
  - pyyaml
  - scikit-learn
  - six
  - tensorboardX
  - tqdm
  # for pip packages, include even if already in pavics-jupyter-base image, to avoid a warning problem on DockerHub
  - pip
  - pip:
    # Install kornia from pypi, versions from conda are older and create conflicting errors with latest python version
    - kornia
    # Use opencv-python-headless instead of opencv or opencv-python.
    # This package is smaller and avoids having to do the full installation of opencv from source.
    # Also, the opencv package was producing some errors during the environment installation and the opencv-python was
    # requiring a prior installation of python3-opencv via apt-get to include additional required library files.
    - opencv-python-headless
    - orion
    - torch
    - torchvision>=0.6
    - Bottleneck==1.3.7
    - cloudpathlib==0.15.1
    - folium==0.14.0
    - geojson==3.0.1
    - getpass4==0.0.14.1
    - requests-file==1.5.1
    - rioxarray==0.15.0
    - sentinelsat==1.2.1
    - weaver@git+https://github.com/crim-ca/weaver.git@4.30.0
    - xarray==2022.11.0
